
module Languate.MD.MDGen where

{--

Helper function to generate a markdown overview page.

--}

import StdDef
import MarkDown
import Text.Pandoc
import Text.Blaze.Html.Renderer.String

import Languate.FQN

import Data.Time

-- Embeds with nice footer and header
generate	:: Name -> MarkDown -> (String -> String -> String) -> IO MarkDown
generate nm md link
		=  do	foot	<- footer link
			return $ title 1 nm ++ parag md ++ foot

generate'	:: Name -> ((String -> String -> String) -> MarkDown) -> (String -> String -> String) -> IO MarkDown
generate' nm md link
		=  do	foot	<- footer link
			return $ title 1 nm ++ parag (md link) ++ foot


saveTo		:: FilePath -> Name -> ((String -> String -> String) -> IO MarkDown) -> IO ()
saveTo fp name md
		=  do	let mdLink txt url	= link txt $ url ++ ".md"
			let htmlLink txt url	= link txt $ url ++ ".html"
			toMd	<- md mdLink
			toHtml	<- md htmlLink
			writeFile (fp++name++".md") toMd
			writeFile (fp++"/html/"++name++".html") $ toHTML toHtml
			putStrLn $ "Saved markdown and html file to "++fp

toHTML		:: MarkDown -> String
toHTML md	=  let  html	= renderHtml . writeHtml def $ readMarkdown (def {readerExtensions = githubMarkdownExtensions}) md in
			htmlHead ++ html ++ htmlFoot


htmlHead	= "<link rel=\"stylesheet\" href=\"github-markdown.css\"><style> .markdown-body {   min-width: 200px;    max-width: 1080;     margin: 0 auto;   padding: 60px;  }</style> <article class=\"markdown-body\">"
htmlFoot	= "</article>"



-- generates a footer with "autogenerated on <date>,"...
footer	:: (String -> String -> String) -> IO MarkDown
footer link
	= do	time	<- getCurrentTime
		zone	<- getCurrentTimeZone
		let remNanos	= takeWhile ('.' /=)
		let date	= remNanos $ show time
		let dateLocal	= remNanos . show $ utcToLocalTime zone time
		let p =  [parag "This page was automatically generated." -- " on "++date++" UTC ("++dateLocal++" "++show zone++")"
			, parag "Do not edit it, as regeneration will overwrite your changes."
			, "Back to "++link "index" "Index"
			]
		return $ qoute $ unlines p
