
module Languate.MD.MDGen where

{--

Helper function to generate a markdown overview page.

--}

import StdDef
import MarkDown

import Languate.FQN

import Data.Time

-- Embeds with nice footer and header
generate	:: Name -> MarkDown -> IO MarkDown
generate nm md
		=  do	foot	<- footer
			return $ title 1 nm ++ parag md ++ foot

saveTo		:: FilePath -> IO MarkDown -> IO ()
saveTo fp md	=  do	txt	<- md
			writeFile fp txt
			putStrLn $ "Saved markdown file to "++fp


-- generates a footer with "autogenerated on <date>,"...
footer	:: IO MarkDown
footer	= do	time	<- getCurrentTime
		zone	<- getCurrentTimeZone
		let remNanos	= fst . break (=='.')
		let date	= remNanos $ show time
		let dateLocal	= remNanos . show $ utcToLocalTime zone time
		let p =  [parag $ "This page was automatically generated on "++date++" UTC ("++dateLocal++" "++show zone++")"
			, "Do not edit it, as regeneration will overwrite your changes."
			]
		return $ qoute $ unlines p
