Manifest

author		"Pieter Vander Vennet"
date		[2015, 03, 03, 22, 22, 42]
desc		"The syntaxis of Manifest files. Also see the manifest example.
		 Manifests consist mainly of 'key ::= value' pairs, which contain all info.
		 The synopsis and description is read from the first comment"


 import Prelude

 manifest	::= globalIdent "\n" line synopsis "\n"+ description "\n"* line (field "\n"+)+

 field		::= localIdent "\t*=" metaValue

 metaValue	::= version | nat | string | localIdent | moduleName | license | dict | set | list

 moduleName	::= (localIdent dot)* globalIdent
 license	::= globalIdent string string | globalIdent
 version	::= nat (dot nat)*

 commaSepValue	::= metaValue (comma metaValue)*
 list		::= "\[" commaSepValue "\]"
 set		::= "\{" commaSepValue "\}"
 dictValue	::= metaValue "-->" metaValue
 dict		::= "\{" dictValue (comma dictValue)* "\}"

$synopsis	::= %"![\n]"+
$description	::= %(("!(---)" "!\n"* "\n")*)
$line		::= "--" "-"+ "\n"*

dot		::= "\."
comma		::= ","
