Comments

author		"Pieter Vander Vennet"
date		[2014, 06, 09, 17, 56, 42]
desc		"The syntaxis of comments. There always is a comment above each declaration, it is the docstring. The documentation tool is for later; it'll be markdown/literate"
 
public import Prelude

-- one or more newlines, with exactly one comment in them
nlcomment	::= "\n"* (mlcomment | comment) "\n"+

nl		::= (mlcomment | comment) ? "\n"
nls		::= nl+
nltab		::=  (mlcomment | comment) ? "\n\t"

$comment		::= "--" "!\n*"
$mlcommentCont	::= "((!-+)|((--!-)|(-!-)))"*
mlcomment	::= "---+" mlcommentCont "---+"

