Comments

author		"Pieter Vander Vennet"
date		[2014, 06, 09, 17, 56, 42]
desc		"The syntaxis of comments. The last comment above a declaration is its docstring."

public import Prelude

-- one or more newlines, with exactly one comment in them
nlcomment	::= "\n"* (mlcomment | comment) "\n"+

nl		::= (mlcomment | comment) ? "\n"
nls		::= nl+
nltab		::=  (mlcomment | comment) ? "\n\t"

comment		::= "--" $%"!\n"*
mlcomment	::= "---+" %$( "!-+" | "--!-|-!-" | "[ \t]")*  "---+"
nlcomments	::= nlcomment+
