Imports

author		"Pieter Vander Vennet"
date		[2014, 06, 12, 19, 27, 42]
desc		"The syntaxis of imports in Languate"

import Prelude
import Expressions

_id		::= localIdent | globalIdent | op | "\(" op "\)"
limiters	::= ("hiding" | "showing") "\{" id (comma? id)* "\}"
import		::= "public"? "import" %((globalIdent dot)* globalIdent) limiters?

_dot		::= %"\."
_comma		::= ","

