Languate

author		"Pieter Vander Vennet"
date		[2014, 5, 29, 21, 48, 42]
desc		"The syntaxis of the Languate programming language"

import Functions
import Comments
import Expressions
import TypeDefs
import Imports


statement	::= function | nls data | nls synonym | nls subtype
lang	::= globalIdent "\n" nlcomment (nls? import)* statement+ nls

