Languate

author		"Pieter Vander Vennet"
date		[2014, 5, 29, 21, 48, 42]
desc		"The syntaxis of the Languate programming language"

import Types
import Functions
import Comments
import Expressions
import TypeDefs
import Imports
import Annotations
import Manifest showing {manifest} -- Import manifest so that it is loaded


{- Where it all begins -}

statement	::=  function | law | data | synonym | subtype | cat | instance | precedence | annotation | nls

module		::= globalIdent idSet? nl nlcomment (nls? import)* nls? statement* 
